blog/urls.py
from blog.apps import BlogConfig
from django.urls import path
from blog.views import (
    PostsListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
)


app_name = BlogConfig.name

urlpatterns = [
    path("posts/", PostsListView.as_view(), name="posts_list"),
    path("posts/create/", PostCreateView.as_view(), name="post_create"),
    path("posts/<int:pk>/update/", PostUpdateView.as_view(), name="post_update"),
    path("posts/<int:pk>/delete/", PostDeleteView.as_view(), name="post_delete"),
    path("posts/<int:pk>/", PostDetailView.as_view(), name="post_detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.db.models.manager import Manager


class Post(models.Model):
    title = models.CharField(
        max_length=150, verbose_name="Заголовок поста", help_text="Введите заголовок"
    )
    content = models.TextField(verbose_name="Текст поста", help_text="Введите текст")
    image = models.ImageField(
        upload_to="img_of_blog_post/",
        blank=True,
        null=True,
        verbose_name="Изображение для поста блога",
    )
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата создания поста"
    )
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name="Дата редактирования поста"
    )
    publication_flag = models.BooleanField(
        default=False, verbose_name="Признак публикации"
    )
    views_count = models.IntegerField(default=0, verbose_name="Количество просмотров")
    # Для линтера
    objects: Manager["Post"]

    def __str__(self):
        result_content = str(self.content)
        if len(result_content) > 30:
            result_content = result_content[:30] + "..."
        return f"{self.title} {result_content}"

    def __repr__(self):
        result_content = str(self.content)
        if len(result_content) > 30:
            result_content = result_content[:30] + "..."
        return f"{self.title} {result_content}"

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"
        ordering = ["created_at"]

blog/views.py
from django.urls import reverse_lazy

from blog.models import Post

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView


class PostsListView(ListView):
    model = Post
    template_name = "blog/posts_list.html"
    context_object_name = "posts"

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(publication_flag=True)
        return queryset


class PostDetailView(DetailView):
    model = Post
    template_name = "blog/post_detail.html"
    context_object_name = "post"

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class PostCreateView(CreateView):
    model = Post
    template_name = "blog/post_form.html"
    fields = (
        "title",
        "content",
        "image",
        "publication_flag",
    )
    success_url = reverse_lazy("blog:posts_list")


class PostUpdateView(UpdateView):
    model = Post
    template_name = "blog/post_form.html"
    fields = (
        "title",
        "content",
        "image",
    )

    def get_success_url(self):
        return reverse_lazy("blog:post_detail", kwargs={"pk": self.object.pk})


class PostDeleteView(DeleteView):
    model = Post
    template_name = "blog/delete_post.html"
    success_url = reverse_lazy("blog:posts_list")

blog/templates/blog/includes/inc_menu.html
{% load static %}
<!--suppress HtmlUnknownTarget -->
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container">
        <a class="navbar-brand" href="{% url 'blog:posts_list' %}">
            <img alt="Главная" style="height: 40px;" class="navbar-logo"
                src="{% static 'blog/img/logo/shopaholics_logo_light.png' %}"
                data-logo-light="{% static 'blog/img/logo/shopaholics_logo_dark.png' %}"
                data-logo-dark="{% static 'blog/img/logo/shopaholics_logo_light.png' %}">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'blog:post_create' %}">+ Добавить пост</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:posts_list' %}">Блог</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Контакты</a>
                </li>
            </ul>
        </div>
    </div>
</nav>