blog/urls.py
from blog.apps import BlogConfig
from django.urls import path
from blog.views import (
    PostsListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
)


app_name = BlogConfig.name

urlpatterns = [
    path("posts/", PostsListView.as_view(), name="posts_list"),
    path("posts/create/", PostCreateView.as_view(), name="post_create"),
    path("posts/<int:pk>/update/", PostUpdateView.as_view(), name="post_update"),
    path("posts/<int:pk>/delete/", PostDeleteView.as_view(), name="post_delete"),
    path("posts/<int:pk>/", PostDetailView.as_view(), name="post_detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.db.models.manager import Manager


class Post(models.Model):
    title = models.CharField(
        max_length=150, verbose_name="Заголовок поста", help_text="Введите заголовок"
    )
    content = models.TextField(verbose_name="Текст поста", help_text="Введите текст")
    image = models.ImageField(
        upload_to="img_of_blog_post/",
        blank=True,
        null=True,
        verbose_name="Изображение для поста блога",
    )
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата создания поста"
    )
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name="Дата редактирования поста"
    )
    publication_flag = models.BooleanField(
        default=False, verbose_name="Признак публикации"
    )
    views_count = models.IntegerField(default=0, verbose_name="Количество просмотров")
    # Для линтера
    objects: Manager["Post"]

    def __str__(self):
        result_content = str(self.content)
        if len(result_content) > 30:
            result_content = result_content[:30] + "..."
        return f"{self.title} {result_content}"

    def __repr__(self):
        result_content = str(self.content)
        if len(result_content) > 30:
            result_content = result_content[:30] + "..."
        return f"{self.title} {result_content}"

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"
        ordering = ["created_at"]

blog/views.py
from django.urls import reverse_lazy

from blog.models import Post

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView


class PostsListView(ListView):
    model = Post
    template_name = "blog/posts_list.html"
    context_object_name = "posts"

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(publication_flag=True)
        return queryset


class PostDetailView(DetailView):
    model = Post
    template_name = "blog/post_detail.html"
    context_object_name = "post"

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class PostCreateView(CreateView):
    model = Post
    template_name = "blog/post_form.html"
    fields = (
        "title",
        "content",
        "image",
        "publication_flag",
    )
    success_url = reverse_lazy("blog:posts_list")


class PostUpdateView(UpdateView):
    model = Post
    template_name = "blog/post_form.html"
    fields = (
        "title",
        "content",
        "image",
    )

    def get_success_url(self):
        return reverse_lazy("blog:post_detail", kwargs={"pk": self.object.pk})


class PostDeleteView(DeleteView):
    model = Post
    template_name = "blog/delete_post.html"
    success_url = reverse_lazy("blog:posts_list")

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<!--suppress HtmlUnknownTarget -->
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Astro v5.13.2">
    <title>Блог Шопоголики</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">
    <script src="{% static 'blog/js/color-modes.js' %}"></script>
    <link href="{% static 'blog/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="apple-touch-icon" href="{% static 'blog/img/favicons/apple-touch-icon.png' %}" sizes="180x180">
    <link rel="icon" href="{% static 'blog/img/favicons/favicon-32x32.png' %}" sizes="32x32" type="image/png">
    <link rel="icon" href="{% static 'blog/img/favicons/favicon-16x16.png' %}" sizes="16x16" type="image/png">
    <link rel="manifest" href="{% static 'blog/img/favicons/manifest.json' %}">
    <link rel="mask-icon" href="{% static 'blog/img/favicons/safari-pinned-tab.svg' %}" color="#712cf9">
    <link rel="icon" href="{% static 'blog/img/favicons/favicon.ico' %}">
    <meta name="theme-color" content="#712cf9">
    <style>
        .bd-placeholder-img{font-size:1.125rem;text-anchor:middle;-webkit-user-select:none;-moz-user-select:none;user-select:none}@media (min-width: 768px){.bd-placeholder-img-lg{font-size:3.5rem}}.b-example-divider{width:100%;height:3rem;background-color:#0000001a;border:solid rgba(0,0,0,.15);border-width:1px 0;box-shadow:inset 0 .5em 1.5em #0000001a,inset 0 .125em .5em #00000026}.b-example-vr{flex-shrink:0;width:1.5rem;height:100vh}.bi{vertical-align:-.125em;fill:currentColor}.nav-scroller{position:relative;z-index:2;height:2.75rem;overflow-y:hidden}.nav-scroller .nav{display:flex;flex-wrap:nowrap;padding-bottom:1rem;margin-top:-1px;overflow-x:auto;text-align:center;white-space:nowrap;-webkit-overflow-scrolling:touch}.btn-bd-primary{--bd-violet-bg: #712cf9;--bd-violet-rgb: 112.520718, 44.062154, 249.437846;--bs-btn-font-weight: 600;--bs-btn-color: var(--bs-white);--bs-btn-bg: var(--bd-violet-bg);--bs-btn-border-color: var(--bd-violet-bg);--bs-btn-hover-color: var(--bs-white);--bs-btn-hover-bg: #6528e0;--bs-btn-hover-border-color: #6528e0;--bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);--bs-btn-active-color: var(--bs-btn-hover-color);--bs-btn-active-bg: #5a23c8;--bs-btn-active-border-color: #5a23c8}.bd-mode-toggle{z-index:1500}.bd-mode-toggle .bi{width:1em;height:1em}.bd-mode-toggle .dropdown-menu .active .bi{display:block!important}
    </style>
</head>
<body>
<!--Иконки переключения тем (темная/светлая)-->
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"></path>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"></path>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"></path>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"></path>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"></path>
    </symbol>
</svg>
<!--Переключатель тем (темная/светлая)-->
<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center" id="bd-theme" type="button"
            aria-expanded="false" data-bs-toggle="dropdown" aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" aria-hidden="true">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span></button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" aria-hidden="true">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" aria-hidden="true">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" aria-hidden="true">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" aria-hidden="true">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50" aria-hidden="true">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" aria-hidden="true">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>
<header>
    {% include 'blog/includes/inc_menu.html' %}
</header>
<main>
    <section class="py-3 text-center container">
        <div class="row py-lt-3 pb-lg-5">
            <div class="col-lg-10 col-md-8 mx-auto text-start">
                <h1 class="fw-light">Shopaholics</h1>
                <p class="lead text-body-secondary">
                    Блог для людей увлеченных покупками. Тут только честные обзоры и отзывы.
                </p>
            </div>
        </div>
    </section>


    {% block content %}
    {% endblock %}

</main>
<footer class="text-body-secondary py-5">
    <div class="container"><p class="float-end mb-1"><a href="#">Back to top</a></p>
        <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p class="mb-0">
            New to Bootstrap? <a href="/">Visit the homepage</a> or read our
            <a href="/docs/5.3/getting-started/introduction">getting started guide</a>.
        </p>
    </div>
</footer>
<script src="{% static 'blog/js/bootstrap.bundle.min.js' %}"></script>
<script>
    function updateNavbarLogo() {
        const theme = document.documentElement.getAttribute('data-bs-theme');
        const logo = document.querySelector('.navbar-logo');

        if (!logo) return;

        if (theme === 'dark') {
            logo.src = logo.dataset.logoDark;
        } else {
            logo.src = logo.dataset.logoLight;
        }
    }

    // при загрузке страницы
    updateNavbarLogo();

    // отслеживаем смену темы
    const observer = new MutationObserver(updateNavbarLogo);
    observer.observe(document.documentElement, {
        attributes: true,
        attributeFilter: ['data-bs-theme']
    });
</script>

</body>
</html>

blog/templates/blog/delete_post.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block content %}
<div class="py-5 bg-body-tertiary">
    <div class="container">
        <div class="card border-0 shadow-sm mx-auto" style="max-width: 700px;">
            <div class="card-body p-4 text-center">

                <!-- Заголовок -->
                <h2 class="text-danger mb-3">Удаление поста</h2>

                <!-- Предупреждение -->
                <p class="fs-5">
                    Вы действительно хотите удалить пост
                    <strong>«{{ object.title }}»</strong>?
                </p>

                <p class="text-muted">
                    Это действие невозможно отменить.
                </p>

                <!-- Кнопки -->
                <form method="post" class="mt-4 d-flex justify-content-center gap-3">
                    {% csrf_token %}

                    <a href="{% url 'blog:post_detail' object.pk %}"
                       class="btn btn-outline-secondary px-4">
                        Отмена
                    </a>

                    <button type="submit"
                            class="btn btn-danger px-4">
                        Удалить
                    </button>
                </form>

            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block content %}
<!--suppress ALL -->
<div class="py-5 bg-body-tertiary">
    <div class="container">
        <div class="card border-0 shadow-sm mx-auto" style="max-width: 900px;">
            <div class="card-body p-4">

                <h2 class="card-title mb-3 text-center">{{ post.title }}</h2>

                {% if post.image %}
                    <img src="{{ post.image|media_filter }}"
                         class="img-fluid rounded mb-4 mt-3 w-100"
                         alt="{{ post.title }}">
                {% endif %}

                <div class="card-text fs-5 mb-4">
                    {{ post.content }}
                </div>

                <div class="d-flex justify-content-between align-items-center mt-5">

                    <!-- Левая группа -->
                    <div class="d-flex align-items-center gap-3">
                        <a href="{% url 'blog:posts_list' %}" class="btn btn-outline-secondary">
                            Назад
                        </a>

                        <span class="text-muted">
                            {{ post.views_count }} &#128065;
                        </span>
                    </div>

                    <!-- Правая группа -->
                    <div class="d-flex align-items-center gap-3">
                        <a href="{% url 'blog:post_update' post.pk %}"
                           class="btn btn-outline-primary ms-auto">
                            Редактировать пост
                        </a>

                        <a href="{% url 'blog:post_delete' post.pk %}"
                           class="btn btn-outline-danger ms-auto">
                            Удалить пост
                        </a>
                    </div>

                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block content %}
<div class="py-5 bg-body-tertiary">
    <div class="container">
        <div class="card border-0 shadow-sm mx-auto" style="max-width: 900px;">
            <div class="card-body p-4">

                <h2 class="text-center mb-4">
                    {% if object %}
                        Редактирование поста
                    {% else %}
                        Создание поста
                    {% endif %}
                </h2>

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <!-- Заголовок -->
                    <div class="mb-3">
                        <label class="form-label">Заголовок</label>
                        {{ form.title|add_class:"form-control" }}
                        {% if form.title.errors %}
                            <div class="text-danger small">{{ form.title.errors }}</div>
                        {% endif %}
                    </div>

                    <!-- Контент -->
                    <div class="mb-3">
                        <label class="form-label">Текст поста</label>
                        {{ form.content|add_class:"form-control" }}
                        {% if form.content.errors %}
                            <div class="text-danger small">{{ form.content.errors }}</div>
                        {% endif %}
                    </div>

                    <!-- Изображение -->
                    <div class="mb-4">
                        <label class="form-label">Изображение</label>
                        {{ form.image|add_class:"form-control" }}
                        {% if form.image.errors %}
                            <div class="text-danger small">{{ form.image.errors }}</div>
                        {% endif %}
                    </div>

                    <!-- Кнопки -->
                    <div class="d-flex justify-content-between align-items-center">
                        <a href="{% url 'blog:posts_list' %}" class="btn btn-outline-secondary">Назад</a>
                        <button type="submit" class="btn btn-primary px-4">
                            {% if object %}Сохранить изменения{% else %}Создать пост{% endif %}
                        </button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/posts_list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for post in posts %}
                <div class="col">
                    <div class="card shadow-sm">
                        <img src="{{ post.image|media_filter }}" alt="нет изображения" class="card-img-top" style="aspect-ratio: 1/1; object-fit: cover;">
                        <div class="card-body">
                            <h5 class="card-text">{{ post.title|truncatechars:30 }}</h5>
                            <p class="card-text" style="min-height: 85px">{{ post.content|truncatechars:100 }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a type="button" title="Открыть пост" class="btn btn-sm btn-outline-secondary" href="{% url 'blog:post_detail' post.pk %}">Открыть пост</a>
                                    <a type="button" title="Поставить лайк" class="btn btn-sm btn-outline-secondary">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                            <path d="M12 21C12 21 4 13.736 4 8.5C4 5.462 6.462 3 9.5 3C11.24 3 12 4.118 12 4.118C12 4.118 12.76 3 14.5 3C17.538 3 20 5.462 20 8.5C20 13.736 12 21 12 21Z"/>
                                        </svg>
                                    </a>
                                </div>
                                <small class="text-body-secondary">{{ post.views_count }} &#128065;</small>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}