blog/urls.py
from blog.apps import BlogConfig
from django.urls import path
from blog.views import (
    PostsListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
)


app_name = BlogConfig.name

urlpatterns = [
    path("posts/", PostsListView.as_view(), name="posts_list"),
    path("posts/create/", PostCreateView.as_view(), name="post_create"),
    path("posts/<int:pk>/update/", PostUpdateView.as_view(), name="post_update"),
    path("posts/<int:pk>/delete/", PostDeleteView.as_view(), name="post_delete"),
    path("posts/<int:pk>/", PostDetailView.as_view(), name="post_detail"),
]

catalog/urls.py
from catalog.apps import CatalogConfig
from django.urls import path

from catalog.views import (
    ProductsListView,
    ProductDetailView,
    ContactsTemplateView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
)

app_name = CatalogConfig.name

urlpatterns = [
    path("catalog/", ProductsListView.as_view(), name="product_list"),
    path(
        "catalog/product/<int:pk>/detail/",
        ProductDetailView.as_view(),
        name="product_detail",
    ),
    path("catalog/product/add/", ProductCreateView.as_view(), name="add_product"),
    path(
        "catalog/product/<int:pk>/update/",
        ProductUpdateView.as_view(),
        name="update_product",
    ),
    path(
        "catalog/product/<int:pk>/delete/",
        ProductDeleteView.as_view(),
        name="delete_product",
    ),
    path("catalog/contacts/", ContactsTemplateView.as_view(), name="contacts"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification


app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
]

catalog/models.py
from django.db import models
from django.db.models.manager import Manager


class Category(models.Model):
    name = models.CharField(
        max_length=150,
        verbose_name="Наименование категории",
        help_text="Введите категорию",
    )
    description = models.TextField(
        verbose_name="Описание категории", help_text="Введите категорию"
    )
    # Для линтера
    objects: Manager["Category"]

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"
        ordering = ["name"]


class Product(models.Model):
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, verbose_name="Категория"
    )
    name = models.CharField(
        max_length=150,
        verbose_name="Наименование продукта",
        help_text="Введите наименование",
    )
    description = models.TextField(
        verbose_name="Описание продукта", help_text="Введите Описание"
    )
    image = models.ImageField(
        upload_to="products/",
        blank=True,
        null=True,
        verbose_name="Изображение продукта",
    )
    price = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name="Цена продукта"
    )
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата создания продукта"
    )
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name="Дата редактирования продукта"
    )
    # Для линтера
    objects: Manager["Product"]

    def __str__(self):
        return f"{self.name} {self.price}"

    def __repr__(self):
        return f"{self.name} {self.price}"

    class Meta:
        verbose_name = "продукт"
        verbose_name_plural = "продукты"
        ordering = ["name"]

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.files.uploadedfile import UploadedFile

from catalog.models import Product, Category
from catalog.constants import FORBIDDEN_WORDS, MAX_IMAGE_SIZE, ALLOWED_IMAGE_FORMATS


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = (
            "name",
            "description",
        )

    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)

        self.fields["name"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите название категории"}
        )

        self.fields["description"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите описание категории"}
        )


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ("name", "description", "image", "price", "category")

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)

        self.fields["name"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите название продукта"}
        )

        self.fields["description"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите описание продукта"}
        )

        self.fields["image"].widget.attrs.update(
            {
                "class": "form-control",
            }
        )

        self.fields["price"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите цену продукта"}
        )

        self.fields["category"].queryset = Category.objects.all()

    def clean_name(self):
        """Проверка на существование добавляемого продукта,
        или не входит ли добавляемое название в список запрещенных"""
        name = self.cleaned_data.get("name")

        # Проверка на существование товара
        qs = Product.objects.filter(name=name)
        if self.instance.pk:
            qs = qs.exclude(pk=self.instance.pk)

        if qs.exists():
            raise ValidationError("Такой товар уже существует")

        # Проверка на наличие запрещенных слов
        forbidden_words_list = FORBIDDEN_WORDS.split()
        for word in forbidden_words_list:
            if word in name.lower():
                raise ValidationError(
                    f'В названии товара есть слово "{word}" входящее в список запрещенных'
                )
        return name

    def clean_price(self):
        """Проверка цены (не может быть отрицательной)"""
        price = self.cleaned_data.get("price")
        if price <= 0:
            raise ValidationError("Цена должна быть положительным числом")
        return price

    def clean_image(self):
        image = self.cleaned_data.get("image")

        if not image:
            return image

        if image.size > MAX_IMAGE_SIZE:
            raise ValidationError("Размер изображения не должен превышать 5 МБ")

        if isinstance(image, UploadedFile):
            if image.content_type not in ALLOWED_IMAGE_FORMATS:
                raise ValidationError("Допустимы только изображения формата JPEG или PNG")

        return image

catalog/views.py
from catalog.models import Product
from catalog.forms import ProductForm

from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy


class ProductsListView(ListView):
    model = Product
    template_name = "catalog/product_list.html"
    context_object_name = "products"


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = "catalog/product_detail.html"
    context_object_name = "product"


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = "catalog/form_product.html"
    success_url = reverse_lazy("catalog:product_list")


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = "catalog/form_product.html"
    success_url = reverse_lazy("catalog:product_list")


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    template_name = "catalog/confirm_delete.html"
    success_url = reverse_lazy("catalog:product_list")


class ContactsTemplateView(TemplateView):
    template_name = "catalog/contacts.html"

catalog/templates/catalog/includes/inc_menu.html
<!--suppress ALL -->
<div class="collapse text-bg-dark" id="navbarHeader">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-7 py-4"><h4>Tony Macarony</h4>
                <p class="text-body-secondary">Наш магазин — это пространство современной итальянской моды, где стиль
                    сочетается с качеством и комфортом. Мы предлагаем тщательно подобранные коллекции, созданные из
                    премиальных материалов с вниманием к деталям и идеальной посадке.</p></div>
            <div class="col-sm-4 offset-md-1 py-4 text-end"><h4>Меню</h4>
                <ul class="list-unstyled text-end">
                    <li><a href="{% url 'catalog:product_list' %}" title="Перейти на главную страницу" class="text-white">Главная</a></li>
                    <li><a href="{% url 'catalog:add_product' %}" class="text-white">Добавить товар</a></li>
                    <li><a href="{% url 'catalog:contacts' %}" class="text-white">Контакты</a></li>
                    {% if user.is_authenticated %}
                    <li>
                        <form action="{% url 'users:logout' %}" method="post" class="d-inline">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-link text-white p-0 m-0">Выход</button>
                        </form>
                    </li>
                    {% else %}
                    <li><a href="{% url 'users:login' %}" class="text-white">Вход</a></li>
                    <li><a href="{% url 'users:register' %}" class="text-white">Регистрация</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
        <a href="#" class="navbar-brand d-flex align-items-center"></a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarHeader"
                aria-controls="navbarHeader"
                aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</div>