blog/urls.py
from blog.apps import BlogConfig
from django.urls import path
from blog.views import (
    PostsListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
)


app_name = BlogConfig.name

urlpatterns = [
    path("posts/", PostsListView.as_view(), name="posts_list"),
    path("posts/create/", PostCreateView.as_view(), name="post_create"),
    path("posts/<int:pk>/update/", PostUpdateView.as_view(), name="post_update"),
    path("posts/<int:pk>/delete/", PostDeleteView.as_view(), name="post_delete"),
    path("posts/<int:pk>/", PostDetailView.as_view(), name="post_detail"),
]

catalog/urls.py
from catalog.apps import CatalogConfig
from django.urls import path

from catalog.views import (
    ProductsListView,
    ProductDetailView,
    ContactsTemplateView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
)

app_name = CatalogConfig.name

urlpatterns = [
    path("catalog/", ProductsListView.as_view(), name="product_list"),
    path(
        "catalog/product/<int:pk>/detail/",
        ProductDetailView.as_view(),
        name="product_detail",
    ),
    path("catalog/product/add/", ProductCreateView.as_view(), name="add_product"),
    path(
        "catalog/product/<int:pk>/update/",
        ProductUpdateView.as_view(),
        name="update_product",
    ),
    path(
        "catalog/product/<int:pk>/delete/",
        ProductDeleteView.as_view(),
        name="delete_product",
    ),
    path("catalog/contacts/", ContactsTemplateView.as_view(), name="contacts"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.db.models.manager import Manager


class Category(models.Model):
    name = models.CharField(
        max_length=150,
        verbose_name="Наименование категории",
        help_text="Введите категорию",
    )
    description = models.TextField(
        verbose_name="Описание категории", help_text="Введите категорию"
    )
    # Для линтера
    objects: Manager["Category"]

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"
        ordering = ["name"]


class Product(models.Model):
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, verbose_name="Категория"
    )
    name = models.CharField(
        max_length=150,
        verbose_name="Наименование продукта",
        help_text="Введите наименование",
    )
    description = models.TextField(
        verbose_name="Описание продукта", help_text="Введите Описание"
    )
    image = models.ImageField(
        upload_to="products/",
        blank=True,
        null=True,
        verbose_name="Изображение продукта",
    )
    price = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name="Цена продукта"
    )
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата создания продукта"
    )
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name="Дата редактирования продукта"
    )
    # Для линтера
    objects: Manager["Product"]

    def __str__(self):
        return f"{self.name} {self.price}"

    def __repr__(self):
        return f"{self.name} {self.price}"

    class Meta:
        verbose_name = "продукт"
        verbose_name_plural = "продукты"
        ordering = ["name"]

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.files.uploadedfile import UploadedFile

from catalog.models import Product, Category
from catalog.constants import FORBIDDEN_WORDS, MAX_IMAGE_SIZE, ALLOWED_IMAGE_FORMATS


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = (
            "name",
            "description",
        )

    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)

        self.fields["name"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите название категории"}
        )

        self.fields["description"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите описание категории"}
        )


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ("name", "description", "image", "price", "category")

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)

        self.fields["name"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите название продукта"}
        )

        self.fields["description"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите описание продукта"}
        )

        self.fields["image"].widget.attrs.update(
            {
                "class": "form-control",
            }
        )

        self.fields["price"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите цену продукта"}
        )

        self.fields["category"].queryset = Category.objects.all()

    def clean_name(self):
        """Проверка на существование добавляемого продукта,
        или не входит ли добавляемое название в список запрещенных"""
        name = self.cleaned_data.get("name")

        # Проверка на существование товара
        qs = Product.objects.filter(name=name)
        if self.instance.pk:
            qs = qs.exclude(pk=self.instance.pk)

        if qs.exists():
            raise ValidationError("Такой товар уже существует")

        # Проверка на наличие запрещенных слов
        forbidden_words_list = FORBIDDEN_WORDS.split()
        for word in forbidden_words_list:
            if word in name.lower():
                raise ValidationError(
                    f'В названии товара есть слово "{word}" входящее в список запрещенных'
                )
        return name

    def clean_price(self):
        """Проверка цены (не может быть отрицательной)"""
        price = self.cleaned_data.get("price")
        if price <= 0:
            raise ValidationError("Цена должна быть положительным числом")
        return price

    def clean_image(self):
        image = self.cleaned_data.get("image")

        if not image:
            return image

        if image.size > MAX_IMAGE_SIZE:
            raise ValidationError("Размер изображения не должен превышать 5 МБ")

        if isinstance(image, UploadedFile):
            if image.content_type not in ALLOWED_IMAGE_FORMATS:
                raise ValidationError("Допустимы только изображения формата JPEG или PNG")

        return image

catalog/views.py
from catalog.models import Product
from catalog.forms import ProductForm

from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy


class ProductsListView(ListView):
    model = Product
    template_name = "catalog/product_list.html"
    context_object_name = "products"


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = "catalog/product_detail.html"
    context_object_name = "product"


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = "catalog/form_product.html"
    success_url = reverse_lazy("catalog:product_list")


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = "catalog/form_product.html"
    success_url = reverse_lazy("catalog:product_list")


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    template_name = "catalog/confirm_delete.html"
    success_url = reverse_lazy("catalog:product_list")


class ContactsTemplateView(TemplateView):
    template_name = "catalog/contacts.html"

catalog/templates/catalog/base.html
{% load static %}

<!DOCTYPE html>
<!--suppress HtmlUnknownTarget -->
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Astro v5.13.2">
    <title>Магазин Тони Макарони</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">
    <script src="{% static 'catalog/js/color-modes.js' %}"></script>
    <link href="{% static 'catalog/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="apple-touch-icon" href="{% static 'catalog/img/favicons/apple-touch-icon.png' %}" sizes="180x180">
    <link rel="icon" href="{% static 'catalog/img/favicons/favicon-32x32.png' %}" sizes="32x32" type="image/png">
    <link rel="icon" href="{% static 'catalog/img/favicons/favicon-16x16.png' %}" sizes="16x16" type="image/png">
    <link rel="manifest" href="{% static 'catalog/img/favicons/manifest.json' %}">
    <link rel="mask-icon" href="{% static 'catalog/img/favicons/safari-pinned-tab.svg' %}" color="#712cf9">
    <link rel="icon" href="{% static 'catalog/img/favicons/favicon.ico' %}">
    <meta name="theme-color" content="#712cf9">
    <style>
        .bd-placeholder-img{font-size:1.125rem;text-anchor:middle;-webkit-user-select:none;-moz-user-select:none;user-select:none}@media (min-width: 768px){.bd-placeholder-img-lg{font-size:3.5rem}}.b-example-divider{width:100%;height:3rem;background-color:#0000001a;border:solid rgba(0,0,0,.15);border-width:1px 0;box-shadow:inset 0 .5em 1.5em #0000001a,inset 0 .125em .5em #00000026}.b-example-vr{flex-shrink:0;width:1.5rem;height:100vh}.bi{vertical-align:-.125em;fill:currentColor}.nav-scroller{position:relative;z-index:2;height:2.75rem;overflow-y:hidden}.nav-scroller .nav{display:flex;flex-wrap:nowrap;padding-bottom:1rem;margin-top:-1px;overflow-x:auto;text-align:center;white-space:nowrap;-webkit-overflow-scrolling:touch}.btn-bd-primary{--bd-violet-bg: #712cf9;--bd-violet-rgb: 112.520718, 44.062154, 249.437846;--bs-btn-font-weight: 600;--bs-btn-color: var(--bs-white);--bs-btn-bg: var(--bd-violet-bg);--bs-btn-border-color: var(--bd-violet-bg);--bs-btn-hover-color: var(--bs-white);--bs-btn-hover-bg: #6528e0;--bs-btn-hover-border-color: #6528e0;--bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);--bs-btn-active-color: var(--bs-btn-hover-color);--bs-btn-active-bg: #5a23c8;--bs-btn-active-border-color: #5a23c8}.bd-mode-toggle{z-index:1500}.bd-mode-toggle .bi{width:1em;height:1em}.bd-mode-toggle .dropdown-menu .active .bi{display:block!important}
    </style>
</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"></path>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"></path>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"></path>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"></path>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"></path>
    </symbol>
</svg>
<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center" id="bd-theme" type="button"
            aria-expanded="false" data-bs-toggle="dropdown" aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" aria-hidden="true">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span></button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" aria-hidden="true">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" aria-hidden="true">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" aria-hidden="true">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" aria-hidden="true">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50" aria-hidden="true">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" aria-hidden="true">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>
<header data-bs-theme="dark">
{% include 'catalog/includes/inc_menu.html' %}
</header>
<main>
    <section class="py-3 text-center container">
        <div class="row py-lt-3 pb-lg-5">
            <div class="col-lg-10 col-md-8 mx-auto text-start">
                <h1 class="fw-light">Style by Tony Macarony</h1>
                <p class="lead text-body-secondary">
                    Здесь вы можете приобрести стильную одежду из Италии от дизайнера Тони Макарони.
                </p>
<!--                <p>-->
<!--                    <a href="#" class="btn btn-primary my-2">Main call to action</a>-->
<!--                    <a href="#" class="btn btn-secondary my-2">Secondary action</a>-->
<!--                </p>-->
            </div>
        </div>
    </section>


    {% block content %}
    {% endblock %}

</main>
<footer class="text-body-secondary py-5">
    <div class="container"><p class="float-end mb-1"><a href="#">Back to top</a></p>
        <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p class="mb-0">
            New to Bootstrap? <a href="/">Visit the homepage</a> or read our
            <a href="/docs/5.3/getting-started/introduction">getting started guide</a>.
        </p>
    </div>
</footer>
<script src="{% static 'catalog/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/confirm_delete.html
{% extends 'catalog/base.html' %}
{% load catalog_tags %}
{% block content %}

<!--suppress ALL -->
<div class="py-5 bg-body-tertiary">
    <div class="container">
        <!-- Форма -->
        <div class="card mb-4 border-0 shadow-sm">
            <div class="row g-0">
                <form method="post">
                    {% csrf_token %}

                    <div class="row mb-4">
                        <div class="col-12">
                            <h4 class="text-center">Удалить {{ object.name }}?</h4>
                        </div>
                    </div>

                    <div class="row mb-4">
                        <div class="col-md-4">
                            <img src="{{ object.image|media_filter }}" class="img-fluid rounded-start" alt="нет изображения" style="height: 100%; object-fit: cover;">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <p class="card-text">{{ object.description }}</p>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <!--Кнопки-->
                        <div class="col-12 d-flex justify-content-center gap-2">
                            <button type="submit" class="btn btn-outline-danger d-flex align-items-center gap-1">Удалить товар</button>
                            <a href="{% url 'catalog:product_detail' object.pk %}" class="btn btn-outline-primary d-flex align-items-center gap-1">Отмена</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% load catalog_tags %}
{% block content %}

<div class="py-5 bg-body-tertiary">
    <div class="container">
        <!-- Контакты -->
        <div class="container">
            <h1>Контакты</h1>
            <p>Наш адрес: г. Милан, пр. Моды, д. 123</p>
            <p>Телефон: +7 999 123 45 67</p>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/form_product.html
{% extends 'catalog/base.html' %}
{% load catalog_tags %}
{% block content %}

<div class="py-5 bg-body-tertiary">
    <div class="container">
        <!-- Форма -->
        <div class="card mb-4 border-0 shadow-sm">
            <div class="row g-0">
                <form method="post" enctype="multipart/form-data" class="p-4">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Добавить продукт</button>
                    <!--suppress HtmlUnknownTarget -->
                    <a class="" href="{% if object %}{% url 'catalog:product_detail' object.pk %}{% else %}{% url 'catalog:product_list' %}{% endif %}">
                        Назад
                    </a>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load catalog_tags %}
{% block content %}

<div class="py-5 bg-body-tertiary">
    <div class="container">
        <!-- Одиночная карточка продукта -->
        <div class="card mb-4 border-0 shadow-sm">
            <div class="row g-0">
                <!-- Левая часть: изображение продукта -->
                <div class="col-md-4">
                    <img src="{{ product.image|media_filter }}" class="img-fluid rounded-start" alt="нет изображения" style="height: 100%; object-fit: cover;">
                </div>
                <!-- Правая часть: описание и кнопки -->
                <div class="col-md-8 d-flex flex-column">
                    <div class="card-body flex-grow-1 d-flex flex-column">
                        <h3 class="card-title mb-3">{{ product.name }}</h3>
                        <h5>Категория: {{ product.category }}</h5>
                        <p class="card-text mb-4">{{ product.description }}</p>
                        <div class="mt-auto">
                            <!-- Цена -->
                            <div class="d-flex justify-content-end align-items-center mb-3">
                                <h5 class="mb-0">{{ product.price }} &#8381;</h5>
                            </div>
                            <div class="d-flex justify-content-end align-items-center mb-3">
                                <h5 class="mb-0">В продаже с {{ product.created_at|date:'d M Y' }}</h5>
                            </div>
                            <!--Кнопки-->
                            <div class="d-flex justify-content-between align-items-center mt-2">
                                <!-- Кнопка "Назад" слева -->
                                <a href="{% url 'catalog:product_list' %}" title="Вернутся ко всем товарам" class="btn btn-outline-secondary d-flex align-items-center">Назад</a>
                                <!-- Кнопки справа -->
                                <div class="d-flex gap-2 mt-3">
                                    <a href="{% url 'catalog:delete_product' product.pk %}" title="Удалить продукт" class="btn btn-outline-danger d-flex align-items-center">Удалить товар</a>
                                    <a href="{% url 'catalog:update_product' product.pk %}" title="Редактировать товар" class="btn btn-outline-primary d-flex align-items-center">Редактировать товар</a>
                                    <a title="Добавить в корзину" class="btn btn-outline-secondary d-flex align-items-center">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                             fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                            <path d="M6 19m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" />
                                            <path d="M17 19m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" />
                                            <path d="M17 17h-11v-14h-2" />
                                            <path d="M6 5l14 1l-1 7h-13" />
                                        </svg>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load catalog_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for product in products %}
                <div class="col">
                    <div class="card shadow-sm">
                        <img src="{{ product.image|media_filter }}" alt="нет изображения" class="card-img-top" style="aspect-ratio: 1/1; object-fit: cover;">
                        <div class="card-body">
                            <h5 class="card-text">{{ product.name }}</h5>
                            <p class="card-text" style="min-height: 85px">{{ product.description|truncatechars:100 }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="d-flex gap-2">
                                    <a type="button" title="Открыть карточку товара" class="btn btn-sm btn-outline-secondary" href="{% url 'catalog:product_detail' product.pk %}">Подробнее</a>
                                    <a type="button" title="Добавить в корзину" class="btn btn-sm btn-outline-secondary">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-shopping-cart"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M6 19m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" /><path d="M17 19m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" /><path d="M17 17h-11v-14h-2" /><path d="M6 5l14 1l-1 7h-13" /></svg>
                                    </a>
                                </div>
                                <small class="text-body-secondary">{{ product.price }} &#8381;</small>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}